### ISSUE TITLE
Commands that require the level name do not work, support for & with gradient and hexadecimal colors is missing.

### ISSUE THREAD

**Issue by Zarkness** [CPJiNan/AkariLevel#7]
Hi, @CPJiNan I was testing the version you gave me in this issue #5 and when I put the command /akarilevel exp add <playername> <levelname> 1000 and the same with the level add command, it didn't work and gave me these errors. -> https://paste.helpch.at/dabicaralo.rb 

I think you forgot that I also asked you that for the levels you can also use & together with gradient and hexadecimal colors instead of §. (this I could not test if you added support or not since I did not work the commands).

**Comment by CPJiNan** [comment]
Hi, @Zarkness 

Thank you for helping with the testing!

The issue you encountered might be due to the Kotlin serialization dependency not loading. Please try restarting your server. 
For some unknown reason, the plugin does not automatically enable the dependencies after the initial download. I am currently working on a fix for this.

Regarding hex colors, the colored() function in Taboolib seems to support this feature. This means you can directly use hex color codes. 

For example:

{255-255-255} — RGB code
{255,255,255} — RGB code
{#FFFFFF} — HEX code
{BLUE} — Known color (English)
{蓝} — Known color (Chinese)

**Comment by CPJiNan** [comment]
Hi, @Zarkness 

Thank you for helping with the testing!

The issue you encountered might be due to the Kotlin serialization dependency not loading. Please try restarting your server.
For some unknown reason, the plugin does not automatically enable the dependencies after the initial download. I am currently working on a fix for this.

Regarding hex colors, the colored() function in Taboolib seems to support this feature. This means you can directly use hex color codes like &#FFFF00.

**Comment by CPJiNan** [comment]
Hi, @Zarkness 

Thank you for helping with the testing!

The issue you encountered might be due to the Kotlin serialization dependency not loading. Please try [this](https://github.com/CPJiNan/AkariLevel/actions/runs/9622600122/artifacts/1626962463) build.

Regarding hex colors, the colored() function in Taboolib seems to support this feature. This means you can directly use hex color codes like &{#FFFF00}.

![&{#4C88E4}Hex&{#98F5F9}Color](https://github.com/CPJiNan/AkariLevel/assets/103565669/598a3b5d-1377-4bb9-9b96-0b3c90054856)

**Comment by Zarkness** [comment]
> Hi, @Zarkness
> 
> Thank you for helping with the testing!
> 
> The issue you encountered might be due to the Kotlin serialization dependency not loading. Please try restarting your server. For some unknown reason, the plugin does not automatically enable the dependencies after the initial download. I am currently working on a fix for this.
> 
> Regarding hex colors, the colored() function in Taboolib seems to support this feature. This means you can directly use hex color codes.
> 
> For example:
> 
> {255-255-255} — RGB code {255,255,255} — RGB code {#FFFFFF} — HEX code {BLUE} — Known color (English) {蓝} — Known color (Chinese)

  
With the version that you passed me I already tried restarting the server several times and it is still the same, I did not try with the most recent one.

the colors could not you add support for the format that is used more globally? is that having on one side &b on another \<blue> and another {blue} or for gradients {255-255-255} when normally it is usually \<#7946FD>Text\</#9B76FB> or \<gradient:#7946FD:#9B76FB>Text\</gradient>, is something ugly.

**Comment by Zarkness** [comment]
now it works without any problem and the color theme at least in the level action does not work.

![image](https://github.com/CPJiNan/AkariLevel/assets/48263644/f6aec221-45c4-452c-a285-7850c1401f64)

the akarilevel levelup command does not work with or without op having the necessary permissions.

When I put as before to level 20 a condition now instead of raising me by much xp that I give the user does not rise to level 20 even if you have the permission remains at level 19, this is the config that I have.

I'm not going to bad but I'm getting a little tired of encountering problems with the plugin every now and then.

```yml
# 示例等级组
Example:
  # 展示名称
  Display: "示例等级组"
  # 来源设置
  Source:
    # 监听的经验来源
    # - "VANILLA_EXP_CHANGE"
    Subscribe:
      - "MYTHICMOBS_DROP_EXP"
  # 追踪设置
  # 当玩家追踪某个等级组时，将在原版经验条上显示其经验进度
  Trace:
    # 该等级组是否能被追踪
    Enable: true
    # 追踪该等级组所需条件 (Kether支持, 每行返回值均为 true 时才可追踪)
    # Condition:
    #   - false
    Condition: [ ]
    # 追踪该等级组后执行的动作 (Kether支持)
    Action: [ ]
  # 等级设置
  Level:
    # 最高等级
    Max: 100
    # 满足要求自动升级
    Auto-Levelup: true
    # 达到最大等级后不再获取经验
    Exp-Limit: true
    # 关键等级设置
    # 只需对关键等级进行修改, 处于非关键等级时将自动读取上一个关键等级的信息
    Key:
      # 0 级等级设置
      0:
        # 等级名称
        # %level% -> 对应等级
        Name: "§8Lv.§b0"
        # 升至该等级所需经验 (JavaScript支持)
        # %level% -> 对应等级
        Exp: "0"
        # 升至该等级所需条件 (Kether支持, 每行返回值均为 true 时才可升级)
        # Kether动作列表 https://kether.tabooproject.org/list.html
        # Condition:
        #   - "permission akarilevel.default"
        Condition: [ ]
        # 升级后执行的动作 (Kether支持)
        # Action:
        #   - command inline "give {{sender}} apple 1" as op
        Action: [ ]
      # 1 级 - 49 级(下一个关键等级之前的等级) 等级设置
      1:
        Name: "&{#4C88E4}Lv.§b%level%"
        Exp: "%level% * 5 + 100"
        Condition: [ ]
        Action:
          - title "&{#4C88E4}§lLevel UP!"
          - subtitle inline "{{ papi %akarilevel_lastlevelname% }} §7→ {{ papi %akarilevel_levelname% }}" by 10 20 10
          - actionbar inline "&{#98F5F9}[ §7{{ papi %akarilevel_exp% }} §8/ §7{{ papi %akarilevel_nextlevelexp% }} §8]"
      20:
        Name: "&{#4C88E4}Lv.§b%level%"
        Exp: "%level% * 5 + 100"
        Condition:
          - "permission testing.level.20"
        Action:
          - title "&{#4C88E4}§lLevel UP!"
          - subtitle inline "{{ papi %akarilevel_lastlevelname% }} §7→ {{ papi %akarilevel_levelname% }}" by 10 20 10
          - actionbar inline "&{#98F5F9}[ §7{{ papi %akarilevel_exp% }} §8/ §7{{ papi %akarilevel_nextlevelexp% }} §8]"
      # 50 级 - 100 级(满级) 等级设置
      50:
        Name: "§8Lv.§b%level%"
        Exp: "%level% * 10 + 100"
        Condition: [ ]
        Action:
          - title "§e§lLevel UP!"
          - subtitle inline "{{ papi %akarilevel_lastlevelname% }} §7→ {{ papi %akarilevel_levelname% }}" by 10 20 10
          - actionbar inline "§8[ §7{{ papi %akarilevel_exp% }} §8/ §7{{ papi %akarilevel_nextlevelexp% }} §8]"
```
